version: '3.8'

services:
  # Base de données Airflow (Méta-données)
  airflow-db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=${AIRFLOW_DB_PASSWORD}
      - POSTGRES_DB=airflow
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Initialisation Airflow (crée l'admin automatiquement)
  airflow-init:
    build: .
    depends_on:
      airflow-db:
        condition: service_healthy
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:${AIRFLOW_DB_PASSWORD}@airflow-db/airflow
      - AIRFLOW__WEBSERVER__SECRET_KEY=${AIRFLOW__WEBSERVER__SECRET_KEY}
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - _AIRFLOW_WWW_USER_USERNAME=${AIRFLOW_ADMIN_USER}
      - _AIRFLOW_WWW_USER_PASSWORD=${AIRFLOW_ADMIN_PASSWORD}
      - _AIRFLOW_WWW_USER_EMAIL=${AIRFLOW_EMAIL}
      - _AIRFLOW_WWW_USER_ROLE=Admin
      - TZ=Europe/Paris
    user: "${AIRFLOW_UID:-50000}:0"
    command:
      - bash
      - -c
      - |
        airflow db migrate &&
        airflow users create \
          --username "${AIRFLOW_ADMIN_USER}" \
          --password "${AIRFLOW_ADMIN_PASSWORD}" \
          --firstname Admin \
          --lastname User \
          --role Admin \
          --email "${AIRFLOW_EMAIL}" || true

          
  # Webserver Airflow
  airflow-webserver:
    build: .
    container_name: airflow-webserver
    depends_on:
      airflow-init:
        condition: service_completed_successfully
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:${AIRFLOW_DB_PASSWORD}@airflow-db/airflow
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__WEBSERVER__SECRET_KEY=${AIRFLOW__WEBSERVER__SECRET_KEY}
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - TZ=Europe/Paris
      - POSTGRES_USER=${POSTGRES_DB_USER}
      - POSTGRES_PASSWORD=${POSTGRES_DB_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - MONGODB_URI=${MONGODB_URI}
      - AIRFLOW_CONN_POSTGRES_DATA=${DB_URL}
    ports:
      - "8081:8080"
    volumes:
      - .:/opt/airflow
      - ./dags:/opt/airflow/dags
      - ./scripts:/opt/airflow/scripts
      - ./drivers:/opt/spark/drivers
    user: "${AIRFLOW_UID:-50000}:0"
    command: webserver

  # Scheduler Airflow
  airflow-scheduler:
    build: .
    container_name: airflow-scheduler
    depends_on:
      airflow-init:
        condition: service_completed_successfully
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:${AIRFLOW_DB_PASSWORD}@airflow-db/airflow
      - AIRFLOW__WEBSERVER__SECRET_KEY=${AIRFLOW__WEBSERVER__SECRET_KEY}
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - POSTGRES_USER=${POSTGRES_DB_USER}
      - POSTGRES_PASSWORD=${POSTGRES_DB_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - MONGODB_URI=${MONGODB_URI}
      - TZ=Europe/Paris
      - AIRFLOW_CONN_POSTGRES_DATA=${DB_URL}
      
      - DB_URL=${DB_URL}
      # Variables pour ton bot
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
    volumes:
      - .:/opt/airflow
      - ./dags:/opt/airflow/dags
      - ./scripts:/opt/airflow/scripts
      - ./spark_jobs:/opt/spark/spark_jobs
      - ./drivers:/opt/spark/drivers
    user: "${AIRFLOW_UID:-50000}:0"
    command: scheduler

  # Base de données métier (Smart Buy)
  postgres_data:
    image: postgres:13-alpine
    container_name: postgres_data
    environment:
      - POSTGRES_USER=${POSTGRES_DB_USER}
      - POSTGRES_PASSWORD=${POSTGRES_DB_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}

  # --- SERVICES SPARK ---
  spark-master:
    image: apache/spark:3.5.0
    container_name: spark-master
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master
    ports:
      - "8082:8080"
    volumes:
      - ./data:/opt/airflow/data
      - ./spark_jobs:/opt/spark/spark_jobs
      - ./drivers:/opt/spark/drivers

  spark-worker:
    image: apache/spark:3.5.0
    container_name: spark-worker
    depends_on:
      - spark-master
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    environment:
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=1G
    volumes:
      - ./data:/opt/airflow/data
      - ./spark_jobs:/opt/spark/spark_jobs
      - ./drivers:/opt/spark/drivers

  # --- INTERFACE WEB ---
  webapp:
    image: python:3.9-slim
    container_name: streamlit-app
    depends_on:
      - postgres_data
    volumes:
      - ./streamlit-app:/app
      - ./data:/data
    environment:
      - DB_URL=${DB_URL}
    working_dir: /app
    command: sh -c "pip install streamlit pandas psycopg2-binary plotly sqlalchemy python-dotenv && streamlit run app_web.py"
    ports:
      - "8501:8501"